### ISSUE TITLE
Adding duplicate tracks

### ISSUE THREAD

**Issue by ghost** [Belisarith/jammming#1]
https://github.com/Belisarith/jammming/blob/master/src/Components/App/App.js#L64-L67

This is an interesting way to check if a track has been added to the playlist previously and definitely gets the job done, but it's not the most efficient. By definition, the every() method checks _every_ element in an array and determines _every_ element meets some condition.

In reality, you don't need to check every single element. If you find a single element with the matching track id, that's enough to know that you shouldn't add the new track. You don't need to continue checking the IDs of all the other tracks after that.

Could you use any other `Array` methods to accomplish this that may be more efficient? One method that comes to mind is [`.some()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some), which merely checks if _any_ element in the array meets the condition.

```javascript
if (this.state.playlistTracks.some(_track => _track.id === track.id))
```

**Comment by Belisarith** [comment]
Thx, for the recommondation. Will be implemented.
